propel:
  _attributes: { package: plugins.opIntroFriendPlugin.lib.model }

  intro_friend:
     id: ~
     from_id:   { type: integer, foreignTable: member, foreignReference: id }
     to_id:     { type: integer, foreignTable: member, foreignReference: id }
     content:   { type: longvarchar }
     updated_at: ~
